<?php

namespace Database\Seeders;

use App\Models\Capacidad;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CapacidadsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $capacidads = [
            [155, 'Capacidad de comunicar ideas de manera efectiva, tanto de forma oral como escrita.', 1, 1],
            [156, 'Capacidad de comunicar ideas de manera efectiva, tanto de forma oral como escrita.', 2, 1],
            [157, 'Capacidad de comunicar ideas de manera efectiva, tanto de forma oral como escrita.', 3, 1],
            [158, 'Capacidad de comunicar ideas de manera efectiva, tanto de forma oral como escrita.', 4, 1],
            [159, 'Capacidad de comunicar ideas de manera efectiva, tanto de forma oral como escrita.', 5, 1],
            [160, 'Capacidad de comunicar ideas de manera efectiva, tanto de forma oral como escrita.', 6, 1],
            [161, 'Capacidad para resolver problemas complejos utilizando conceptos matemáticos y razonamiento lógico.', 7, 1],
            [162, 'Capacidad para resolver problemas complejos utilizando conceptos matemáticos y razonamiento lógico.', 8, 1],
            [163, 'Capacidad para resolver problemas complejos utilizando conceptos matemáticos y razonamiento lógico.', 9, 1],
            [164, 'Capacidad para resolver problemas complejos utilizando conceptos matemáticos y razonamiento lógico.', 10, 1],
            [165, 'Capacidad para resolver problemas complejos utilizando conceptos matemáticos y razonamiento lógico.', 11, 1],
            [166, 'Capacidad para resolver problemas complejos utilizando conceptos matemáticos y razonamiento lógico.', 12, 1],
            [167, 'Capacidad para comprender y aplicar conceptos científicos y tecnológicos en la resolución de problemas del mundo real.', 13, 1],
            [168, 'Capacidad para comprender y aplicar conceptos científicos y tecnológicos en la resolución de problemas del mundo real.', 14, 1],
            [169, 'Capacidad para comprender y aplicar conceptos científicos y tecnológicos en la resolución de problemas del mundo real.', 15, 1],
            [170, 'Capacidad para comprender y aplicar conceptos científicos y tecnológicos en la resolución de problemas del mundo real.', 16, 1],
            [171, 'Capacidad para comprender y aplicar conceptos científicos y tecnológicos en la resolución de problemas del mundo real.', 17, 1],
            [172, 'Capacidad para comprender y aplicar conceptos científicos y tecnológicos en la resolución de problemas del mundo real.', 18, 1],
            [173, 'Capacidad para desarrollar habilidades sociales y emocionales, incluida la empatía y la autorregulación emocional.', 19, 1],
            [174, 'Capacidad para desarrollar habilidades sociales y emocionales, incluida la empatía y la autorregulación emocional.', 20, 1],
            [175, 'Capacidad para desarrollar habilidades sociales y emocionales, incluida la empatía y la autorregulación emocional.', 21, 1],
            [176, 'Capacidad para desarrollar habilidades sociales y emocionales, incluida la empatía y la autorregulación emocional.', 22, 1],
            [177, 'Capacidad para desarrollar habilidades sociales y emocionales, incluida la empatía y la autorregulación emocional.', 23, 1],
            [178, 'Capacidad para desarrollar habilidades sociales y emocionales, incluida la empatía y la autorregulación emocional.', 24, 1],
            [179, 'Capacidad para comprender y respetar diferentes creencias religiosas y éticas, así como explorar preguntas espirituales y éticas personales.', 26, 1],
            [180, 'Capacidad para comprender y respetar diferentes creencias religiosas y éticas, así como explorar preguntas espirituales y éticas personales.', 27, 1],
            [181, 'Capacidad para comprender y respetar diferentes creencias religiosas y éticas, así como explorar preguntas espirituales y éticas personales.', 28, 1],
            [182, 'Capacidad para comprender y respetar diferentes creencias religiosas y éticas, así como explorar preguntas espirituales y éticas personales.', 29, 1],
            [183, 'Capacidad para comprender y respetar diferentes creencias religiosas y éticas, así como explorar preguntas espirituales y éticas personales.', 30, 1],
            [184, 'Capacidad para comprender y respetar diferentes creencias religiosas y éticas, así como explorar preguntas espirituales y éticas personales.', 31, 1],
            [185, 'Capacidad para apreciar y participar en actividades artísticas y culturales, así como expresar la creatividad de forma visual o escénica.', 32, 1],
            [186, 'Capacidad para apreciar y participar en actividades artísticas y culturales, así como expresar la creatividad de forma visual o escénica.', 33, 1],
            [187, 'Capacidad para apreciar y participar en actividades artísticas y culturales, así como expresar la creatividad de forma visual o escénica.', 34, 1],
            [188, 'Capacidad para apreciar y participar en actividades artísticas y culturales, así como expresar la creatividad de forma visual o escénica.', 35, 1],
            [189, 'Capacidad para apreciar y participar en actividades artísticas y culturales, así como expresar la creatividad de forma visual o escénica.', 36, 1],
            [190, 'Capacidad para apreciar y participar en actividades artísticas y culturales, así como expresar la creatividad de forma visual o escénica.', 37, 1],
            [191, 'Capacidad para mantener un estilo de vida activo y saludable, así como desarrollar habilidades físicas y coordinación motora.', 38, 1],
            [192, 'Capacidad para mantener un estilo de vida activo y saludable, así como desarrollar habilidades físicas y coordinación motora.', 39, 1],
            [193, 'Capacidad para mantener un estilo de vida activo y saludable, así como desarrollar habilidades físicas y coordinación motora.', 40, 1],
            [194, 'Capacidad para mantener un estilo de vida activo y saludable, así como desarrollar habilidades físicas y coordinación motora.', 41, 1],
            [195, 'Capacidad para mantener un estilo de vida activo y saludable, así como desarrollar habilidades físicas y coordinación motora.', 42, 1],
            [196, 'Capacidad para mantener un estilo de vida activo y saludable, así como desarrollar habilidades físicas y coordinación motora.', 43, 1],
            [197, 'Se desenvuelve de manera autónoma a través de su motricidad.', 43, 0],
            [198, 'Asume una vida saludable.', 43, 0],
            [199, 'Interactúa a través de sus habilidades socio motrices.', 43, 0],
            [200, 'Se desenvuelve de manera autónoma a través de su motricidad.', 42, 0],
            [201, 'Asume una vida saludable.', 42, 0],
            [202, 'Interactúa a través de sus habilidades socio motrices.', 42, 0],
            [203, 'Se desenvuelve de manera autónoma a través de su motricidad.', 41, 0],
            [204, 'Asume una vida saludable.', 41, 0],
            [205, 'Interactúa a través de sus habilidades socio motrices.', 41, 0],
            [206, 'Se desenvuelve de manera autónoma a través de su motricidad.', 40, 0],
            [207, 'Asume una vida saludable.', 40, 0],
            [208, 'Interactúa a través de sus habilidades socio motrices.', 40, 0],
            [209, 'Se desenvuelve de manera autónoma a través de su motricidad.', 39, 0],
            [210, 'Asume una vida saludable.', 39, 0],
            [211, 'Interactúa a través de sus habilidades socio motrices.', 39, 0],
            [212, 'Se desenvuelve de manera autónoma a través de su motricidad.', 38, 0],
            [213, 'Asume una vida saludable.', 38, 0],
            [214, 'Interactúa a través de sus habilidades socio motrices.', 38, 0],
            [215, 'Aprecia de manera critica manifestaciones artístico-cultural.', 37, 0],
            [216, 'Crea proyectos desde los lenguajes artísticos.', 37, 0],
            [217, 'Aprecia de manera critica manifestaciones artístico-cultural.', 36, 0],
            [218, 'Crea proyectos desde los lenguajes artísticos.', 36, 0],
            [219, 'Aprecia de manera critica manifestaciones artístico-cultural.', 35, 0],
            [220, 'Crea proyectos desde los lenguajes artísticos.', 35, 0],
            [221, 'Aprecia de manera critica manifestaciones artístico-cultural.', 34, 0],
            [222, 'Crea proyectos desde los lenguajes artísticos.', 34, 0],
            [223, 'Aprecia de manera critica manifestaciones artístico-cultural.', 33, 0],
            [224, 'Crea proyectos desde los lenguajes artísticos.', 33, 0],
            [225, 'Aprecia de manera critica manifestaciones artístico-cultural.', 32, 0],
            [226, 'Crea proyectos desde los lenguajes artísticos.', 32, 0],
            [227, 'Construye su identidad como persona humana, amada por Dios, digna, libre y trascendente, comprendiendo la doctrina de su propia religión, abierto al diálogo con las que le son cercanas.', 31, 0],
            [228, 'Asume la experiencia del encuentro personal y comunitario con Dios en su proyecto de vida en coherencia con su creencia religiosa.', 31, 0],
            [229, 'Construye su identidad como persona humana, amada por Dios, digna, libre y trascendente, comprendiendo la doctrina de su propia religión, abierto al diálogo con las que le son cercanas.', 30, 0],
            [230, 'Asume la experiencia del encuentro personal y comunitario con Dios en su proyecto de vida en coherencia con su creencia religiosa.', 30, 0],
            [231, 'Construye su identidad como persona humana, amada por Dios, digna, libre y trascendente, comprendiendo la doctrina de su propia religión, abierto al diálogo con las que le son cercanas.', 29, 0],
            [232, 'Asume la experiencia del encuentro personal y comunitario con Dios en su proyecto de vida en coherencia con su creencia religiosa.', 29, 0],
            [233, 'Construye su identidad como persona humana, amada por Dios, digna, libre y trascendente, comprendiendo la doctrina de su propia religión, abierto al diálogo con las que le son cercanas.', 28, 0],
            [234, 'Asume la experiencia del encuentro personal y comunitario con Dios en su proyecto de vida en coherencia con su creencia religiosa.', 28, 0],
            [235, 'Construye su identidad como persona humana, amada por Dios, digna, libre y trascendente, comprendiendo la doctrina de su propia religión, abierto al diálogo con las que le son cercanas.', 27, 0],
            [236, 'Asume la experiencia del encuentro personal y comunitario con Dios en su proyecto de vida en coherencia con su creencia religiosa.', 27, 0],
            [237, 'Construye su identidad como persona humana, amada por Dios, digna, libre y trascendente, comprendiendo la doctrina de su propia religión, abierto al diálogo con las que le son cercanas.', 26, 0],
            [238, 'Asume la experiencia del encuentro personal y comunitario con Dios en su proyecto de vida en coherencia con su creencia religiosa.', 26, 0],
            [239, 'Construye su identidad.', 24, 0],
            [240, 'Convive y participa democráticamente en la búsqueda del bien común.', 24, 0],
            [241, 'Construye interpretaciones históricas.', 24, 0],
            [242, 'Gestiona responsablemente el espacio y el ambiente.', 24, 0],
            [243, 'Gestiona responsablemente los recursos económicos.', 24, 0],
            [244, 'Construye su identidad.', 23, 0],
            [245, 'Convive y participa democráticamente en la búsqueda del bien común.', 23, 0],
            [246, 'Construye interpretaciones históricas.', 23, 0],
            [247, 'Gestiona responsablemente el espacio y el ambiente.', 23, 0],
            [248, 'Gestiona responsablemente los recursos económicos.', 23, 0],
            [249, 'Construye su identidad.', 22, 0],
            [250, 'Convive y participa democráticamente en la búsqueda del bien común.', 22, 0],
            [251, 'Construye interpretaciones históricas.', 22, 0],
            [252, 'Gestiona responsablemente el espacio y el ambiente.', 22, 0],
            [253, 'Gestiona responsablemente los recursos económicos.', 22, 0],
            [254, 'Construye su identidad.', 21, 0],
            [255, 'Convive y participa democráticamente en la búsqueda del bien común.', 21, 0],
            [256, 'Construye interpretaciones históricas.', 21, 0],
            [257, 'Gestiona responsablemente el espacio y el ambiente.', 21, 0],
            [258, 'Gestiona responsablemente los recursos económicos.', 21, 0],
            [259, 'Construye su identidad.', 20, 0],
            [260, 'Convive y participa democráticamente en la búsqueda del bien común.', 20, 0],
            [261, 'Construye interpretaciones históricas.', 20, 0],
            [262, 'Gestiona responsablemente el espacio y el ambiente.', 20, 0],
            [263, 'Gestiona responsablemente los recursos económicos.', 20, 0],
            [264, 'Construye su identidad.', 19, 0],
            [265, 'Convive y participa democráticamente en la búsqueda del bien común.', 19, 0],
            [266, 'Construye interpretaciones históricas.', 19, 0],
            [267, 'Gestiona responsablemente el espacio y el ambiente.', 19, 0],
            [268, 'Gestiona responsablemente los recursos económicos.', 19, 0],
            [269, 'Indaga mediante métodos científicos para construir sus conocimientos.', 18, 0],
            [270, 'Explica el mundo físico basándose en conocimientos sobre los seres vivos, materia, energía, biodiversidad, tierra y universo.', 18, 0],
            [271, 'Diseña y construye soluciones tecnológicas para resolver problemas de su entorno.', 18, 0],
            [272, 'Indaga mediante métodos científicos para construir sus conocimientos.', 17, 0],
            [273, 'Explica el mundo físico basándose en conocimientos sobre los seres vivos, materia, energía, biodiversidad, tierra y universo.', 17, 0],
            [274, 'Diseña y construye soluciones tecnológicas para resolver problemas de su entorno.', 17, 0],
            [275, 'Indaga mediante métodos científicos para construir sus conocimientos.', 16, 0],
            [276, 'Explica el mundo físico basándose en conocimientos sobre los seres vivos, materia, energía, biodiversidad, tierra y universo.', 16, 0],
            [277, 'Diseña y construye soluciones tecnológicas para resolver problemas de su entorno.', 16, 0],
            [278, 'Indaga mediante métodos científicos para construir sus conocimientos.', 15, 0],
            [279, 'Explica el mundo físico basándose en conocimientos sobre los seres vivos, materia, energía, biodiversidad, tierra y universo.', 15, 0],
            [280, 'Diseña y construye soluciones tecnológicas para resolver problemas de su entorno.', 15, 0],
            [281, 'Indaga mediante métodos científicos para construir sus conocimientos.', 14, 0],
            [282, 'Explica el mundo físico basándose en conocimientos sobre los seres vivos, materia, energía, biodiversidad, tierra y universo.', 14, 0],
            [283, 'Diseña y construye soluciones tecnológicas para resolver problemas de su entorno.', 14, 0],
            [284, 'Indaga mediante métodos científicos para construir sus conocimientos.', 13, 0],
            [285, 'Explica el mundo físico basándose en conocimientos sobre los seres vivos, materia, energía, biodiversidad, tierra y universo.', 13, 0],
            [286, 'Diseña y construye soluciones tecnológicas para resolver problemas de su entorno.', 13, 0],
            [287, 'Resuelve problemas de cantidad.', 12, 0],
            [288, 'Resuelve problemas de regularidad, equivalencia y cambio.', 12, 0],
            [289, 'Resuelve problemas de forma, movimiento y localización.', 12, 0],
            [290, 'Resuelve problemas de gestión de datos e incertidumbre.', 12, 0],
            [291, 'Resuelve problemas de cantidad.', 11, 0],
            [292, 'Resuelve problemas de regularidad, equivalencia y cambio.', 11, 0],
            [293, 'Resuelve problemas de forma, movimiento y localización.', 11, 0],
            [294, 'Resuelve problemas de gestión de datos e incertidumbre.', 11, 0],
            [295, 'Resuelve problemas de cantidad.', 10, 0],
            [296, 'Resuelve problemas de regularidad, equivalencia y cambio.', 10, 0],
            [297, 'Resuelve problemas de forma, movimiento y localización.', 10, 0],
            [298, 'Resuelve problemas de gestión de datos e incertidumbre.', 10, 0],
            [299, 'Resuelve problemas de cantidad.', 9, 0],
            [300, 'Resuelve problemas de regularidad, equivalencia y cambio.', 9, 0],
            [301, 'Resuelve problemas de forma, movimiento y localización.', 9, 0],
            [302, 'Resuelve problemas de gestión de datos e incertidumbre.', 9, 0],
            [303, 'Resuelve problemas de cantidad.', 8, 0],
            [304, 'Resuelve problemas de regularidad, equivalencia y cambio.', 8, 0],
            [305, 'Resuelve problemas de forma, movimiento y localización.', 8, 0],
            [306, 'Resuelve problemas de gestión de datos e incertidumbre.', 8, 0],
            [307, 'Resuelve problemas de cantidad.', 7, 0],
            [308, 'Resuelve problemas de regularidad, equivalencia y cambio.', 7, 0],
            [309, 'Resuelve problemas de forma, movimiento y localización.', 7, 0],
            [310, 'Resuelve problemas de gestión de datos e incertidumbre.', 7, 0],
            [311, 'Se comunica oralmente en su lengua materna.', 6, 0],
            [312, 'Lee diversos tipos de textos en su lengua materna.', 6, 0],
            [313, 'Escribe diversos tipos de textos en su lengua materna.', 6, 0],
            [314, 'Se comunica oralmente en su lengua materna.', 5, 0],
            [315, 'Lee diversos tipos de textos en su lengua materna.', 5, 0],
            [316, 'Escribe diversos tipos de textos en su lengua materna.', 5, 0],
            [317, 'Se comunica oralmente en su lengua materna.', 4, 0],
            [318, 'Lee diversos tipos de textos en su lengua materna.', 4, 0],
            [319, 'Escribe diversos tipos de textos en su lengua materna.', 4, 0],
            [320, 'Se comunica oralmente en su lengua materna.', 3, 0],
            [321, 'Lee diversos tipos de textos en su lengua materna.', 3, 0],
            [322, 'Escribe diversos tipos de textos en su lengua materna.', 3, 0],
            [323, 'Se comunica oralmente en su lengua materna.', 2, 0],
            [324, 'Lee diversos tipos de textos en su lengua materna.', 2, 0],
            [325, 'Escribe diversos tipos de textos en su lengua materna.', 2, 0],
            [326, 'Se comunica oralmente en su lengua materna.', 1, 0],
            [327, 'Lee diversos tipos de textos en su lengua materna.', 1, 0],
            [328, 'Escribe diversos tipos de textos en su lengua materna.', 1, 0],
            [329, 'Rendimiento académico', 44, 0],
            [330, 'Habilidades de estudio', 44, 0],
            [331, 'Motivación y actitud hacia el aprendizaje', 44, 0],
            [332, 'Rendimiento académico', 45, 0],
            [333, 'Habilidades de estudio', 45, 0],
            [334, 'Motivación y actitud hacia el aprendizaje', 45, 0],
            [335, 'Rendimiento académico', 46, 0],
            [336, 'Habilidades de estudio', 46, 0],
            [337, 'Motivación y actitud hacia el aprendizaje', 46, 0],
            [338, 'Rendimiento académico', 47, 0],
            [339, 'Habilidades de estudio', 47, 0],
            [340, 'Motivación y actitud hacia el aprendizaje', 47, 0],
            [341, 'Rendimiento académico', 48, 0],
            [342, 'Habilidades de estudio', 48, 0],
            [343, 'Motivación y actitud hacia el aprendizaje', 48, 0],
            [344, 'Rendimiento académico', 49, 0],
            [345, 'Habilidades de estudio', 49, 0],
            [346, 'Motivación y actitud hacia el aprendizaje', 49, 0],
            [347, 'Habilidades Básicas en Informática', 50, 0],
            [348, 'Resolución de Problemas', 50, 0],
            [349, 'Creatividad y Proyectos Personales', 50, 0],
            [350, 'Habilidades Básicas en Informática', 51, 0],
            [351, 'Resolución de Problemas', 51, 0],
            [352, 'Creatividad y Proyectos Personales', 51, 0],
            [353, 'Habilidades Básicas en Informática', 52, 0],
            [354, 'Resolución de Problemas', 52, 0],
            [355, 'Creatividad y Proyectos Personales', 52, 0],
            [356, 'Habilidades Básicas en Informática', 53, 0],
            [357, 'Resolución de Problemas', 53, 0],
            [358, 'Creatividad y Proyectos Personales', 53, 0],
            [359, 'Habilidades Básicas en Informática', 54, 0],
            [360, 'Resolución de Problemas', 54, 0],
            [361, 'Creatividad y Proyectos Personales', 54, 0],
            [362, 'Habilidades Básicas en Informática', 55, 0],
            [363, 'Resolución de Problemas', 55, 0],
            [364, 'Creatividad y Proyectos Personales', 55, 0],
        ];

        foreach ($capacidads as $asignarCurso) {
             Capacidad::create([
                'cap_id' => $asignarCurso[0],
                'cap_descripcion' => $asignarCurso[1],
                'cur_id' => $asignarCurso[2],
                'cap_is_deleted' => $asignarCurso[3],
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL
            ]);
        }
    }
}
